/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Employer } from "./Employer";
import { EmployerCountArgs } from "./EmployerCountArgs";
import { EmployerFindManyArgs } from "./EmployerFindManyArgs";
import { EmployerFindUniqueArgs } from "./EmployerFindUniqueArgs";
import { CreateEmployerArgs } from "./CreateEmployerArgs";
import { UpdateEmployerArgs } from "./UpdateEmployerArgs";
import { DeleteEmployerArgs } from "./DeleteEmployerArgs";
import { JobVacancyFindManyArgs } from "../../jobVacancy/base/JobVacancyFindManyArgs";
import { JobVacancy } from "../../jobVacancy/base/JobVacancy";
import { EmployerService } from "../employer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Employer)
export class EmployerResolverBase {
  constructor(
    protected readonly service: EmployerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "read",
    possession: "any",
  })
  async _employersMeta(
    @graphql.Args() args: EmployerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Employer])
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "read",
    possession: "any",
  })
  async employers(
    @graphql.Args() args: EmployerFindManyArgs
  ): Promise<Employer[]> {
    return this.service.employers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Employer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "read",
    possession: "own",
  })
  async employer(
    @graphql.Args() args: EmployerFindUniqueArgs
  ): Promise<Employer | null> {
    const result = await this.service.employer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Employer)
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "create",
    possession: "any",
  })
  async createEmployer(
    @graphql.Args() args: CreateEmployerArgs
  ): Promise<Employer> {
    return await this.service.createEmployer({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Employer)
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "update",
    possession: "any",
  })
  async updateEmployer(
    @graphql.Args() args: UpdateEmployerArgs
  ): Promise<Employer | null> {
    try {
      return await this.service.updateEmployer({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Employer)
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "delete",
    possession: "any",
  })
  async deleteEmployer(
    @graphql.Args() args: DeleteEmployerArgs
  ): Promise<Employer | null> {
    try {
      return await this.service.deleteEmployer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [JobVacancy], { name: "jobVacancies" })
  @nestAccessControl.UseRoles({
    resource: "JobVacancy",
    action: "read",
    possession: "any",
  })
  async findJobVacancies(
    @graphql.Parent() parent: Employer,
    @graphql.Args() args: JobVacancyFindManyArgs
  ): Promise<JobVacancy[]> {
    const results = await this.service.findJobVacancies(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
